site_name: Joknarf Tools
site_url: https://joknarf.github.io/joknarf-tools/
repo_url: https://github.com/joknarf/joknarf-tools
repo_name: joknarf-tools
theme:
  name: material
nav:
  - Home: index.md
  - Shell plugins:
    - Thefly: thefly.md
    - Shell-ng: shell-ng.md
    - Selector: selector.md
    - Nerdp: nerdp.md
    - Redo: redo.md
    - Seedee: seedee.md
    - Complete-ng: complete-ng.md
  - Command Line:
    - Pgtree: pgtree.md
    - Run-para: run-para.md
    - Ssh-para: ssh-para.md
    - Portune: portune.md
    - Mkshz: mkshz.md
    - Targpg: targpg.md
  - Web tools:
    - Pywebfs: pywebfs.md
    - Pywebexec: pywebexec.md
  - Fuse fs:
    - Fuse-sshautofs: fuse-sshautofs.md
    - Fuse-memfs: fuse-memfs.md

plugins:
  - search
  # - mkdocs-material if using Material theme

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/joknarf
